apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Chart.Name }}-configmap
data: # Remember this contains passwords - might be an idea to use secrets and environment variables instead.
  chirpstack-network-server.toml: |
    # See https://www.chirpstack.io/network-server/install/config/ for a full
    # configuration example and documentation.
    #
    # This file is for the EU868 band. See the examples/ folder for more
    # configuration examples.
    [general]
    log_level=5

    [postgresql]
    dsn="postgres://chirpstack_ns:chirpstack_ns@postgres-svc/chirpstack_ns?sslmode=disable"

    [redis]
    url="redis://redis-svc:6379"

    [network_server]
    net_id="000000"

    [network_server.band]
    name="EU868"

    [network_server.network_settings]

      [[network_server.network_settings.extra_channels]]
      frequency=867100000
      min_dr=0
      max_dr=5

      [[network_server.network_settings.extra_channels]]
      frequency=867300000
      min_dr=0
      max_dr=5

      [[network_server.network_settings.extra_channels]]
      frequency=867500000
      min_dr=0
      max_dr=5

      [[network_server.network_settings.extra_channels]]
      frequency=867700000
      min_dr=0
      max_dr=5

      [[network_server.network_settings.extra_channels]]
      frequency=867900000
      min_dr=0
      max_dr=5

    [network_server.gateway.backend.mqtt]
    server="tcp://mosquitto-svc:1883"

    [join_server.default]
    server="http://chirpstack-application-server-svc:8003"
